### PR TITLE
actualize gc.su sync script

### PR DESCRIPTION
**Pull request by okainov**
- Use HTTPS since gc.su has migrated finally
- Add short description of the purpose and cron schedule

### CODE REVIEW

**Comment by okainov** [comment]
I have no idea how often is it being run, so `daily` was just my guess, please confirm :)

**Comment by kumy** [comment]
Thanks.

Sync is one time per day https://github.com/geokrety/geokrety-scripts/blob/master/geokrety-crontab#L20

**Comment by okainov** [comment]
BTW from our side I increased the frequency and now we call export_oc.php from GK every 2 hours.

Also btw on GK website it's written that you sync with us every 2 hours as well :)
https://geokrety.org/help.php#fullysupportedwaypoints

**Comment by kumy** [comment]
Please change our frequency updtae rate in the open PR you ve made

**Comment by kumy** [comment]
I ve found the/an exports link in #328 https://api.geokrety.org/basex/export/ I agree it's not expected place and need to be fixed.

https://api.geokrety.org/basex/export/ are refreshed every 5 min, do you think they may be used on your side in place of oc_export?

**Comment by kumy** [comment]
Those are full exports, but we may easily propose exports for timespan like "changed last 2 hours", or have the endpoint from the xml database accepting `modifiedsince` parameter.

**Comment by okainov** [comment]
I think the current model with having endpoint for quick refresh (small amount of data, ok to be called several times per hour) and endpoint for full refresh (whole big chunk of data) is still good enough. It could be one endpoint for sure (`?modifiedsince=1h` vs `?modifiedsince=3000d`), but in general it's still different use cases

**Comment by okainov** [comment]
any updates here?

**Comment by okainov** [comment]
@kumy we just migrated to UTF8,I forgot to update it here so now there are at least several badly synced GKs (see https://geokrety.org/konkret.php?id=70695)

Could you please merge this PR and do full refetch from our DB? Thanks

**Comment by kumy** [comment]
Ho, sorry I missed that one.

**Review by kumy — APPROVED** [review]

**Comment by kumy** [comment]
Done.

**Comment by okainov** [comment]
Thanks 🙏

**Pull request merged**
