### PR TITLE
Fixes #4 waypoint/oc xml2sql.php mass import

### LINKED ISSUE #4: waypoint/oc  xml2sql.php error duplicate stop the mass import
## HowToReproduce ?

Execute the following command

```
cd /opt/geokrety-scripts/waypointy/oc && php xml2sql.php
```

waypoint should be imported  in one shot, but the mass import stop at the first error, ex:

```
error 1: 138028 INSERT INTO `gk-waypointy` ( `waypoint`, `lat` , `lon` , `name` , `owner`,  `typ`, `kraj` , `link`, `status`)
VALUES ('OC888B',  '50.95977', '7.11358', 'Einsatz an der Steinbreche  (#2)' //...//
ON DUPLICATE KEY UPDATE `waypoint`='OC888B', `lat`='50.9 //...//
```

## suggested fix

on duplicate log as warn and continue

### PR DESCRIPTION
**Pull request by boly38**
Fixes #4 waypoint/oc xml2sql.php mass import
 - remove deprecated xml2sql-new.php
 - add exception handling for xml2sql.php
 - add mysqli_real_escape_string for imported string
 - add counter and better report
 - add error file

--
@kumy would suggest to rerun the script on prod without commit #464aa8f25000fa36cdaef25a9d08088a340d2caa

### CODE REVIEW

**Comment by kumy** [comment]
Will check it on monday

**Comment by kumy** [comment]
I trust your judgement, I ll do required action on monday

**Comment by boly38** [comment]
Yep, (minor) keep en eye on the fact that produced file `data-xml` is now appended (could grow over the time) If you want to reset at script startup, we could copy the same pattern as for the (*new*) error log file :)

```
file_put_contents($importErrorsFile, "");
```

becomes

```
file_put_contents($importErrorsFile, "");
file_put_contents($importHistoricFile, "");
 
```

**Comment by kumy** [comment]
New version deployed gradually. Many caches were added. @boly38  congrats for the catch and fix 👏

FYI, Here are the stats:
```
# cat data-xml.txt
 de pl uk us nl;2019-03-24 20:30:472019-03-24 20:38:44;OC;de;17744;17744;0
2019-03-24 20:38:44;OC;de;17744;17744;0
2019-03-24 20:38:45;OP;pl;0;0;0
2019-03-24 20:39:03;OK;uk;461;461;0
2019-03-24 20:39:20;OB;nl;439;439;0
2019-03-24 20:39:48;OK;uk;461;461;0
2019-03-24 20:39:51;OB;nl;439;439;0
2019-03-24 20:41:38;OC;de;0;0;0
2019-03-24 20:41:39;OP;pl;1;1;0
2019-03-24 20:41:39;OK;uk;0;0;0
2019-03-24 20:41:41;OB;nl;0;0;0
2019-03-24 20:41:54;OC;de;0;0;0
2019-03-24 20:41:55;OP;pl;1;1;0
2019-03-24 20:41:56;OK;uk;0;0;0
2019-03-24 20:41:57;OB;nl;0;0;0
2019-03-24 20:42:06;OC;de;0;0;0
2019-03-24 20:42:07;OP;pl;1;1;0
2019-03-24 20:42:08;OK;uk;0;0;0
2019-03-24 20:42:09;OB;nl;0;0;0
[…]
```

**Comment by boly38** [comment]
FYI/ from work I had same results as you, but from home I had bunch of update for OP(pl) :

```` 
2019-03-23 19:48:19;OC;de;17709;17687;22
2019-03-23 21:16:38;OP;pl;24941;24941;0
2019-03-23 21:18:14;OK;uk;461;461;0
2019-03-23 21:19:36;OB;nl;438;438;0
````

**Comment by kumy** [comment]
There is actually 62857 `OP%` waypoints in database, @boly38 what about yours?

**Comment by boly38** [comment]
I got much less (at work)

```` 
- OC% 49,414
- OP% 24,912
- OK% 1,157
- OB% 6,980
```` 

btw this compare seems not relevant because prod got historical entries.
(using same timestamp as bottom range I had found strange that you got no OP but you might have run the import with timestamp line commented.)

**Pull request merged**
